### ISSUE TITLE
Clean up the button management portal for client facing

### ISSUE THREAD

**Issue by TroyScarbrough** [aphelionz/dingdongdash#14]
We need to clean up the button management portal after it has been added to the sales website so it is easier to use and better matching of the front end website.

- [x] Add a section about how to setup a button on wifi, so when someone gets the button they can set it up and manage their notifications seamlessly

**Comment by aphelionz** [comment]
I have the most control over colors here, as well as the right column. I think we can fit most of what you're looking for there.
