### ISSUE TITLE
User Dashboard - Buy another Button Link & Like Us on Social 

### ISSUE THREAD

**Issue by TroyScarbrough** [aphelionz/dingdongdash#40]
Maybe at the bottom of the dashboard or in the top right we need to provide a link back to the home page of the sales website to buy another button.

We should also add a footer that is similar to the sales website that includes social media linking etc to promote people engaging us

**Comment by aphelionz** [comment]
@TroyScarbrough The "View Site" link is that. We can change the text of what it says... what should it say?

Roger that on the footer

**Comment by TroyScarbrough** [comment]
Probably "Store" or "Store Home Page"

Troy Scarbrough
978-885-3195
troyscarbrough@hotmail.com<mailto:troyscarbrough@hotmail.com>

Please excuse any typing errors as this was sent from my mobile device.

On Jun 5, 2017, at 9:07 PM, Mark Robert Henderson <notifications@github.com<mailto:notifications@github.com>> wrote:


@TroyScarbrough<https://github.com/troyscarbrough> The "View Site" link is that. We can change the text of what it says... what should it say?

Roger that on the footer
